### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by howardroark** [duojs/package#58]
Looks like there may be a type at line 101?

```
/Users/evelo/Documents/Repos/pollinate/node_modules/duo-package/lib/index.js:101
Package.cleanCache = function *() {
                              ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/evelo/Documents/Repos/pollinate/lib/fetch.js:10:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by cristiandouce** [comment]
Support for `node@0.10.x` was dropped since latest `duo-package@0.8`. What version of node are you using?

**Comment by howardroark** [comment]
I just updated to `v0.12.2` and see the same issue.  It happens at the point where I import the module.

**Comment by howardroark** [comment]
Could it be that whoever is testing is using `io.js` and there is a variation in how generators are handled?

**Comment by howardroark** [comment]
I can confirm that my theory seems to be true.  I use nvm and just grabbed io.js... no issue when I run my code that way.

**Comment by dominicbarnes** [comment]
@howardroark You need to use the `--harmony-generators` flag when using node 0.12

**Comment by howardroark** [comment]
Ahhh, got it... Thanks! I'm not a node regular. I guess I'll have to copy
the subcommand logic used in duo.

Well this kinda proves that the consensus driven model of io.js works :)
